name: dmch_gui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file: ^6.1.2
  equatable: ^2.0.3
  http: ^0.13.4
  provider: ^6.0.2
  bloc: ^8.0.3
  window_manager: ^0.2.1
  flutter_bloc: ^8.0.1
  stream_bloc: ^0.4.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.2
  flutter_lints: ^2.0.1
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
