openapi: "3.0.2"
info:
  title: DOME API
  version: "1.0"
servers:
  - url: https://dome.royalcat.su/
paths:
  /files/{user}/{*path}:
    get:
      parameters:
        - $ref: "#/components/parameters/user"
        - $ref: "#/components/parameters/path"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: "#/components/schemas/Entry"
                  - $ref: "#/components/schemas/Entry"

  /files/{user}/{*path}/info.json:
    get:
      parameters:
        - $ref: "#/components/parameters/user"
        - $ref: "#/components/parameters/path"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MediaInfo"
  /files/{user}/{*path}/previews/:
    get:
      parameters:
        - $ref: "#/components/parameters/user"
        - $ref: "#/components/parameters/path"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Entry"

components:
  parameters:
    user:
      name: user
      in: path
      required: true
      schema:
        type: string
      description: User name
    path:
      name: path
      in: path
      required: true
      schema:
        type: string
      description: Path to file
  schemas:
    $ref: "models.yml"
